[package]
name = "mm3d-rs"
version = "0.1.0"
authors = ["Pierre-Eric Pelloux-Prayer"]
build = "build.rs"

[dependencies]
clap = {version = "2.20.5", features = ["yaml"]}

[build-dependencies]
clap = "2.20.5"